FROM python:2.7-alpine

RUN apk add --update --no-cache tini bash gettext build-base
ENTRYPOINT ["/sbin/tini", "--"]
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV LANG=C.UTF-8
